export  const data = [
    {
        id:1,
        cat:'creative',
        title:'title1',
        img:'https://images.pexels.com/photos/164729/pexels-photo-164729.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
    {
        id:2,
        cat:'photography',
        title:'title2',
        img:'https://images.pexels.com/photos/2021348/pexels-photo-2021348.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
    {
        id:3,
        cat:'websol',
        title:'title3',
        img:'https://images.pexels.com/photos/2027394/pexels-photo-2027394.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
    {
        id:4,
        cat:'creative',
        title:'title4',
        img:'https://images.pexels.com/photos/68705/pexels-photo-68705.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
    {
        id:5,
        cat:'photography',
        title:'title4',
        img:'https://images.pexels.com/photos/1770289/pexels-photo-1770289.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
    {
        id:6,
        cat:'creative',
        title:'title6',
        img:'https://images.pexels.com/photos/2016810/pexels-photo-2016810.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
    {
        id:7,
        cat:'photography',
        title:'title7',
        img:'https://images.pexels.com/photos/243989/pexels-photo-243989.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
    {
        id:8,
        cat:'creative',
        title:'title8',
        img:'https://images.pexels.com/photos/3756766/pexels-photo-3756766.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
    {
        id:9,
        cat:'photography',
        title:'title9',
        img:'https://images.pexels.com/photos/1918159/pexels-photo-1918159.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
    },
]